name: gen_tools
version: 0.0.1-dev
author: devoncarew@google.com
description: Tools to generate Chrome App APIs
dependencies:
  args: any
  parsers: any
dev_dependencies:
  browser: any
  unittest: any
